const COMP_INST_OPTS_ORDER = [
  'el',
  'name',
  'parent',
  'functional',
  'delimiters',
  'comments',
  'components',
  'directives',
  'filters',
  'extends',
  'mixins',
  'inheritAttrs',
  'model',
  'props',
  'propsData',
  'data',
  'computed',
  'watch',
  'beforeCreate',
  'created',
  'beforeMount',
  'mounted',
  'beforeUpdate',
  'updated',
  'activated',
  'deactivated',
  'beforeDestroy',
  'destroyed',
  'methods',
  'template',
  'render',
  'renderError',
];

export default COMP_INST_OPTS_ORDER;
